preset: laravel

linting: true

disabled:
  - single_class_element_per_statement
  - short_array_syntax
  - length_ordered_imports

enabled:
  - strict

finder:
  exclude:
    - "tests"
    - "node_modules"
    - "storage"
    - "vendor"
  name:
    - "*.php"
  not-name:
    - "*Stub.php"
  not-contains:
    - "config"

# risky: false
#
# enabled:
#   - long_array_syntax
#   - strict
#   - unalign_double_arrow
#
# disabled:
#   - align_double_arrow
#   - short_array_syntax
#
# finder:
#   exclude:
#     - "tests"
#   name:
#     - "*.php"
#   not-name:
#     - "*Stub.php"
#   contains:
#     - "Foo"
#   not-contains:
#     - "config"
#   path:
#     - "foo/Stuff"
#   not-path:
#     - "libraries"
#   depth:
#     - "< 3"
