language: php

php:
  - 7.0

services:
  - mysql

install:
  - composer install --no-interaction --prefer-source

services:
  - mysql

env:
  global:
    - APP_ENV=testing
    - APP_KEY=base64:xZxpMuqxVqEMWQPQKERSfb81GLOzreobkoTtbK91TqY=
    - DB_CONNECTION=travis
    - DB_TEST_USERNAME=root
    - DB_TEST_PASSWORD=
    - CACHE_DRIVER=array
    - SESSION_DRIVER=array
    - QUEUE_DRIVER=sync

before_script:
  - phpenv config-rm xdebug.ini
  - mysql -e 'create database homestead_test;'
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - php artisan migrate

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_failure:
  - cat storage/logs/laravel.log
  - cat tests/_output/*

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 890f1a9a-81a0-4466-b31a-2806a749d536

notifications:
  email: false
